FROM ubuntu:22.04

ARG USER_ID
ARG GROUP_ID
ARG USER
RUN addgroup --gid $GROUP_ID $USER
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID $USER

RUN  apt-get update \
  && apt-get install -y wget zip unzip \
  && rm -rf /var/lib/apt/lists/*
